"""Create readings table

Revision ID: 121cb7503008
Revises: 
Create Date: 2025-11-16 13:21:50.972830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121cb7503008'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('plant_id', sa.String(), nullable=True),
    sa.Column('lettuce_image_url', sa.String(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('n_ppm', sa.Float(), nullable=True),
    sa.Column('p_ppm', sa.Float(), nullable=True),
    sa.Column('k_ppm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_index(op.f('ix_readings_plant_id'), 'readings', ['plant_id'], unique=False)
    op.create_index(op.f('ix_readings_timestamp'), 'readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_timestamp'), table_name='readings')
    op.drop_index(op.f('ix_readings_plant_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###
